### ISSUE TITLE
Crashing NeoForge server on startup

### ISSUE THREAD

**Issue by StygianEmperor** [LieOnLion/More-Chest-Variants#10]
Server has 95-ish mods, and works fine as long as More Chest Variants isn't loaded, in which case it crashes on startup. I guess the NeoForge version is marked as beta for a reason :)
(More Crafting Tables works fine with the server though.)

I figured this was the right file to include but let me know if you need anything else:
[latest.log](https://github.com/LieOnLion/More-Chest-Variants/files/14936612/latest.log)

**Comment by LieOnLion** [comment]
that was because NeoForge itself was in beta at the time, its gone through a few changes meaning its technicallly not a NeoForge mod but a mod for that specific version of NeoForge
Plus I have grown as a developer, NeoForge is still rather new

A new version should be out in the next week, if not, sometime soon (hopefully)
